### ISSUE TITLE
 Click do not work

### ISSUE THREAD

**Issue by SeonHyungJo** [JaeYeopHan/octodirect#16]
## Description

browser version : chromium 69

단축키로 실행시 화살표로 선택 후 Enter를 누를 경우 => 정상 작동 
단축키로 실행시 화살표로 선택 후 마우스 왼쪽 버튼 클릭시 => 미작동 작동

클릭시 해당 페이지로 이동하지 않습니다.

**Comment by JaeYeopHan** [comment]
초기 설계 시 키보드로만 사용할 수 있도록 구성을 했는데요, click event에 대한 부분도 고려해보겠습니다!
이슈 감사합니다 :)
