### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by JaeYeopHan** [JaeYeopHan/octodirect#33]
## Description

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-GgRxrVOKNdB4LrRsVPDSbzvfdV4UqglmviH9GoBJ5jk='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by SoYoung210** [comment]
**Chrome Extensions don't allow you to have inline JavaScript**  
[chrome- contentSecurityPolicy](https://developer.chrome.com/extensions/contentSecurityPolicy#JSExecution)

https://stackoverflow.com/questions/13591983/onclick-within-chrome-extension-not-working

**Comment by JaeYeopHan** [comment]
Thanks @SoYoung210 ! Your comments are helpful!

**Comment by JaeYeopHan** [comment]
https://medium.com/@gilfink/building-a-chrome-extension-using-react-c5bfe45aaf36
